/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChannelRouteImport } from './routes/channel'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as CopyrightPolicyRouteImport } from './routes/copyright-policy'
import { Route as CreateRouteImport } from './routes/create'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrbitRouteImport } from './routes/orbit'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminCopyrightReportsRouteImport } from './routes/admin.copyright-reports'
import { Route as AdminSportsVerificationRouteImport } from './routes/admin.sports-verification'
import { Route as ChannelIndexRouteImport } from './routes/channel.index'
import { Route as ChannelAnalyticsRouteImport } from './routes/channel.analytics'
import { Route as ChannelCreateRouteImport } from './routes/channel.create'
import { Route as ChannelMonetizationRouteImport } from './routes/channel.monetization'
import { Route as ChannelPostsRouteImport } from './routes/channel.posts'
import { Route as ChannelReelsRouteImport } from './routes/channel.reels'
import { Route as ChannelSubscribersRouteImport } from './routes/channel.subscribers'
import { Route as ChannelVideosRouteImport } from './routes/channel.videos'
import { Route as DownloadsDownloadIdRouteImport } from './routes/downloads.$downloadId'
import { Route as MomentIndexRouteImport } from './routes/moment.index'
import { Route as MomentMomentIdRouteImport } from './routes/moment.$momentId'
import { Route as MomentCreateRouteImport } from './routes/moment.create'
import { Route as OrbitIndexRouteImport } from './routes/orbit.index'
import { Route as OrbitProfileIdRouteImport } from './routes/orbit.$profileId'
import { Route as OrbitCreateRouteImport } from './routes/orbit.create'
import { Route as OrbitMeRouteImport } from './routes/orbit.me'
import { Route as OrbitMessagesRouteImport } from './routes/orbit.messages'
import { Route as OrbitNotificationsRouteImport } from './routes/orbit.notifications'
import { Route as OrbitPrivacyRouteImport } from './routes/orbit.privacy'
import { Route as PostCreateRouteImport } from './routes/post.create'
import { Route as ReelReelIdRouteImport } from './routes/reel.$reelId'
import { Route as TermsMonetizationRouteImport } from './routes/terms.monetization'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as VideoVideoIdRouteImport } from './routes/video.$videoId'
import { Route as VideoUploadRouteImport } from './routes/video.upload'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as OrbitChatUserIdRouteImport } from './routes/orbit.chat.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelRoute = ChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightPolicyRoute = CopyrightPolicyRouteImport.update({
  id: '/copyright-policy',
  path: '/copyright-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbitRoute = OrbitRouteImport.update({
  id: '/orbit',
  path: '/orbit',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Verify2faRoute = Verify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCopyrightReportsRoute = AdminCopyrightReportsRouteImport.update({
  id: '/copyright-reports',
  path: '/copyright-reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSportsVerificationRoute = AdminSportsVerificationRouteImport.update({
  id: '/sports-verification',
  path: '/sports-verification',
  getParentRoute: () => AdminRoute,
} as any)
const ChannelIndexRoute = ChannelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChannelRoute,
} as any)
const ChannelAnalyticsRoute = ChannelAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ChannelRoute,
} as any)
const ChannelCreateRoute = ChannelCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ChannelRoute,
} as any)
const ChannelMonetizationRoute = ChannelMonetizationRouteImport.update({
  id: '/monetization',
  path: '/monetization',
  getParentRoute: () => ChannelRoute,
} as any)
const ChannelPostsRoute = ChannelPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => ChannelRoute,
} as any)
const ChannelReelsRoute = ChannelReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => ChannelRoute,
} as any)
const ChannelSubscribersRoute = ChannelSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => ChannelRoute,
} as any)
const ChannelVideosRoute = ChannelVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => ChannelRoute,
} as any)
const DownloadsDownloadIdRoute = DownloadsDownloadIdRouteImport.update({
  id: '/downloads/$downloadId',
  path: '/downloads/$downloadId',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentIndexRoute = MomentIndexRouteImport.update({
  id: '/moment/',
  path: '/moment/',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentMomentIdRoute = MomentMomentIdRouteImport.update({
  id: '/moment/$momentId',
  path: '/moment/$momentId',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentCreateRoute = MomentCreateRouteImport.update({
  id: '/moment/create',
  path: '/moment/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbitIndexRoute = OrbitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitProfileIdRoute = OrbitProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitCreateRoute = OrbitCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitMeRoute = OrbitMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitMessagesRoute = OrbitMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitNotificationsRoute = OrbitNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitPrivacyRoute = OrbitPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => OrbitRoute,
} as any)
const PostCreateRoute = PostCreateRouteImport.update({
  id: '/post/create',
  path: '/post/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelReelIdRoute = ReelReelIdRouteImport.update({
  id: '/reel/$reelId',
  path: '/reel/$reelId',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsMonetizationRoute = TermsMonetizationRouteImport.update({
  id: '/monetization',
  path: '/monetization',
  getParentRoute: () => TermsRoute,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoVideoIdRoute = VideoVideoIdRouteImport.update({
  id: '/video/$videoId',
  path: '/video/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoUploadRoute = VideoUploadRouteImport.update({
  id: '/video/upload',
  path: '/video/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const OrbitChatUserIdRoute = OrbitChatUserIdRouteImport.update({
  id: '/chat/$userId',
  path: '/chat/$userId',
  getParentRoute: () => OrbitRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/channel': typeof ChannelRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/copyright-policy': typeof CopyrightPolicyRoute
  '/create': typeof CreateRoute
  '/help-center': typeof HelpCenterRoute
  '/licenses': typeof LicensesRoute
  '/notifications': typeof NotificationsRoute
  '/orbit': typeof OrbitRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRouteWithChildren
  '/verify-2fa': typeof Verify2faRoute
  '/wallet': typeof WalletRoute
  '/admin/copyright-reports': typeof AdminCopyrightReportsRoute
  '/admin/sports-verification': typeof AdminSportsVerificationRoute
  '/channel/analytics': typeof ChannelAnalyticsRoute
  '/channel/create': typeof ChannelCreateRoute
  '/channel/monetization': typeof ChannelMonetizationRoute
  '/channel/posts': typeof ChannelPostsRoute
  '/channel/reels': typeof ChannelReelsRoute
  '/channel/subscribers': typeof ChannelSubscribersRoute
  '/channel/videos': typeof ChannelVideosRoute
  '/downloads/$downloadId': typeof DownloadsDownloadIdRoute
  '/moment/$momentId': typeof MomentMomentIdRoute
  '/moment/create': typeof MomentCreateRoute
  '/orbit/$profileId': typeof OrbitProfileIdRoute
  '/orbit/create': typeof OrbitCreateRoute
  '/orbit/me': typeof OrbitMeRoute
  '/orbit/messages': typeof OrbitMessagesRoute
  '/orbit/notifications': typeof OrbitNotificationsRoute
  '/orbit/privacy': typeof OrbitPrivacyRoute
  '/post/create': typeof PostCreateRoute
  '/reel/$reelId': typeof ReelReelIdRoute
  '/terms/monetization': typeof TermsMonetizationRoute
  '/u/$userId': typeof UUserIdRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/video/upload': typeof VideoUploadRoute
  '/channel/': typeof ChannelIndexRoute
  '/moment/': typeof MomentIndexRoute
  '/orbit/': typeof OrbitIndexRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/orbit/chat/$userId': typeof OrbitChatUserIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/copyright-policy': typeof CopyrightPolicyRoute
  '/create': typeof CreateRoute
  '/help-center': typeof HelpCenterRoute
  '/licenses': typeof LicensesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRouteWithChildren
  '/verify-2fa': typeof Verify2faRoute
  '/wallet': typeof WalletRoute
  '/admin/copyright-reports': typeof AdminCopyrightReportsRoute
  '/admin/sports-verification': typeof AdminSportsVerificationRoute
  '/channel/analytics': typeof ChannelAnalyticsRoute
  '/channel/create': typeof ChannelCreateRoute
  '/channel/monetization': typeof ChannelMonetizationRoute
  '/channel/posts': typeof ChannelPostsRoute
  '/channel/reels': typeof ChannelReelsRoute
  '/channel/subscribers': typeof ChannelSubscribersRoute
  '/channel/videos': typeof ChannelVideosRoute
  '/downloads/$downloadId': typeof DownloadsDownloadIdRoute
  '/moment/$momentId': typeof MomentMomentIdRoute
  '/moment/create': typeof MomentCreateRoute
  '/orbit/$profileId': typeof OrbitProfileIdRoute
  '/orbit/create': typeof OrbitCreateRoute
  '/orbit/me': typeof OrbitMeRoute
  '/orbit/messages': typeof OrbitMessagesRoute
  '/orbit/notifications': typeof OrbitNotificationsRoute
  '/orbit/privacy': typeof OrbitPrivacyRoute
  '/post/create': typeof PostCreateRoute
  '/reel/$reelId': typeof ReelReelIdRoute
  '/terms/monetization': typeof TermsMonetizationRoute
  '/u/$userId': typeof UUserIdRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/video/upload': typeof VideoUploadRoute
  '/channel': typeof ChannelIndexRoute
  '/moment': typeof MomentIndexRoute
  '/orbit': typeof OrbitIndexRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/orbit/chat/$userId': typeof OrbitChatUserIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/channel': typeof ChannelRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/copyright-policy': typeof CopyrightPolicyRoute
  '/create': typeof CreateRoute
  '/help-center': typeof HelpCenterRoute
  '/licenses': typeof LicensesRoute
  '/notifications': typeof NotificationsRoute
  '/orbit': typeof OrbitRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRouteWithChildren
  '/verify-2fa': typeof Verify2faRoute
  '/wallet': typeof WalletRoute
  '/admin/copyright-reports': typeof AdminCopyrightReportsRoute
  '/admin/sports-verification': typeof AdminSportsVerificationRoute
  '/channel/analytics': typeof ChannelAnalyticsRoute
  '/channel/create': typeof ChannelCreateRoute
  '/channel/monetization': typeof ChannelMonetizationRoute
  '/channel/posts': typeof ChannelPostsRoute
  '/channel/reels': typeof ChannelReelsRoute
  '/channel/subscribers': typeof ChannelSubscribersRoute
  '/channel/videos': typeof ChannelVideosRoute
  '/downloads/$downloadId': typeof DownloadsDownloadIdRoute
  '/moment/$momentId': typeof MomentMomentIdRoute
  '/moment/create': typeof MomentCreateRoute
  '/orbit/$profileId': typeof OrbitProfileIdRoute
  '/orbit/create': typeof OrbitCreateRoute
  '/orbit/me': typeof OrbitMeRoute
  '/orbit/messages': typeof OrbitMessagesRoute
  '/orbit/notifications': typeof OrbitNotificationsRoute
  '/orbit/privacy': typeof OrbitPrivacyRoute
  '/post/create': typeof PostCreateRoute
  '/reel/$reelId': typeof ReelReelIdRoute
  '/terms/monetization': typeof TermsMonetizationRoute
  '/u/$userId': typeof UUserIdRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/video/upload': typeof VideoUploadRoute
  '/channel/': typeof ChannelIndexRoute
  '/moment/': typeof MomentIndexRoute
  '/orbit/': typeof OrbitIndexRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/orbit/chat/$userId': typeof OrbitChatUserIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/channel'
    | '/community-guidelines'
    | '/copyright-policy'
    | '/create'
    | '/help-center'
    | '/licenses'
    | '/notifications'
    | '/orbit'
    | '/privacy'
    | '/profile'
    | '/reels'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-2fa'
    | '/wallet'
    | '/admin/copyright-reports'
    | '/admin/sports-verification'
    | '/channel/analytics'
    | '/channel/create'
    | '/channel/monetization'
    | '/channel/posts'
    | '/channel/reels'
    | '/channel/subscribers'
    | '/channel/videos'
    | '/downloads/$downloadId'
    | '/moment/$momentId'
    | '/moment/create'
    | '/orbit/$profileId'
    | '/orbit/create'
    | '/orbit/me'
    | '/orbit/messages'
    | '/orbit/notifications'
    | '/orbit/privacy'
    | '/post/create'
    | '/reel/$reelId'
    | '/terms/monetization'
    | '/u/$userId'
    | '/video/$videoId'
    | '/video/upload'
    | '/channel/'
    | '/moment/'
    | '/orbit/'
    | '/chat/$threadId'
    | '/orbit/chat/$userId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/community-guidelines'
    | '/copyright-policy'
    | '/create'
    | '/help-center'
    | '/licenses'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/reels'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-2fa'
    | '/wallet'
    | '/admin/copyright-reports'
    | '/admin/sports-verification'
    | '/channel/analytics'
    | '/channel/create'
    | '/channel/monetization'
    | '/channel/posts'
    | '/channel/reels'
    | '/channel/subscribers'
    | '/channel/videos'
    | '/downloads/$downloadId'
    | '/moment/$momentId'
    | '/moment/create'
    | '/orbit/$profileId'
    | '/orbit/create'
    | '/orbit/me'
    | '/orbit/messages'
    | '/orbit/notifications'
    | '/orbit/privacy'
    | '/post/create'
    | '/reel/$reelId'
    | '/terms/monetization'
    | '/u/$userId'
    | '/video/$videoId'
    | '/video/upload'
    | '/channel'
    | '/moment'
    | '/orbit'
    | '/chat/$threadId'
    | '/orbit/chat/$userId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account'
    | '/admin'
    | '/auth'
    | '/channel'
    | '/community-guidelines'
    | '/copyright-policy'
    | '/create'
    | '/help-center'
    | '/licenses'
    | '/notifications'
    | '/orbit'
    | '/privacy'
    | '/profile'
    | '/reels'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-2fa'
    | '/wallet'
    | '/admin/copyright-reports'
    | '/admin/sports-verification'
    | '/channel/analytics'
    | '/channel/create'
    | '/channel/monetization'
    | '/channel/posts'
    | '/channel/reels'
    | '/channel/subscribers'
    | '/channel/videos'
    | '/downloads/$downloadId'
    | '/moment/$momentId'
    | '/moment/create'
    | '/orbit/$profileId'
    | '/orbit/create'
    | '/orbit/me'
    | '/orbit/messages'
    | '/orbit/notifications'
    | '/orbit/privacy'
    | '/post/create'
    | '/reel/$reelId'
    | '/terms/monetization'
    | '/u/$userId'
    | '/video/$videoId'
    | '/video/upload'
    | '/channel/'
    | '/moment/'
    | '/orbit/'
    | '/_authenticated/chat/$threadId'
    | '/orbit/chat/$userId'
    | '/_authenticated/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChannelRoute: typeof ChannelRouteWithChildren
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  CopyrightPolicyRoute: typeof CopyrightPolicyRoute
  CreateRoute: typeof CreateRoute
  HelpCenterRoute: typeof HelpCenterRoute
  LicensesRoute: typeof LicensesRoute
  NotificationsRoute: typeof NotificationsRoute
  OrbitRoute: typeof OrbitRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReelsRoute: typeof ReelsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRouteWithChildren
  Verify2faRoute: typeof Verify2faRoute
  WalletRoute: typeof WalletRoute
  DownloadsDownloadIdRoute: typeof DownloadsDownloadIdRoute
  MomentMomentIdRoute: typeof MomentMomentIdRoute
  MomentCreateRoute: typeof MomentCreateRoute
  PostCreateRoute: typeof PostCreateRoute
  ReelReelIdRoute: typeof ReelReelIdRoute
  UUserIdRoute: typeof UUserIdRoute
  VideoVideoIdRoute: typeof VideoVideoIdRoute
  VideoUploadRoute: typeof VideoUploadRoute
  MomentIndexRoute: typeof MomentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel': {
      id: '/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof ChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright-policy': {
      id: '/copyright-policy'
      path: '/copyright-policy'
      fullPath: '/copyright-policy'
      preLoaderRoute: typeof CopyrightPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orbit': {
      id: '/orbit'
      path: '/orbit'
      fullPath: '/orbit'
      preLoaderRoute: typeof OrbitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/copyright-reports': {
      id: '/admin/copyright-reports'
      path: '/copyright-reports'
      fullPath: '/admin/copyright-reports'
      preLoaderRoute: typeof AdminCopyrightReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sports-verification': {
      id: '/admin/sports-verification'
      path: '/sports-verification'
      fullPath: '/admin/sports-verification'
      preLoaderRoute: typeof AdminSportsVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/channel/': {
      id: '/channel/'
      path: '/'
      fullPath: '/channel/'
      preLoaderRoute: typeof ChannelIndexRouteImport
      parentRoute: typeof ChannelRoute
    }
    '/channel/analytics': {
      id: '/channel/analytics'
      path: '/analytics'
      fullPath: '/channel/analytics'
      preLoaderRoute: typeof ChannelAnalyticsRouteImport
      parentRoute: typeof ChannelRoute
    }
    '/channel/create': {
      id: '/channel/create'
      path: '/create'
      fullPath: '/channel/create'
      preLoaderRoute: typeof ChannelCreateRouteImport
      parentRoute: typeof ChannelRoute
    }
    '/channel/monetization': {
      id: '/channel/monetization'
      path: '/monetization'
      fullPath: '/channel/monetization'
      preLoaderRoute: typeof ChannelMonetizationRouteImport
      parentRoute: typeof ChannelRoute
    }
    '/channel/posts': {
      id: '/channel/posts'
      path: '/posts'
      fullPath: '/channel/posts'
      preLoaderRoute: typeof ChannelPostsRouteImport
      parentRoute: typeof ChannelRoute
    }
    '/channel/reels': {
      id: '/channel/reels'
      path: '/reels'
      fullPath: '/channel/reels'
      preLoaderRoute: typeof ChannelReelsRouteImport
      parentRoute: typeof ChannelRoute
    }
    '/channel/subscribers': {
      id: '/channel/subscribers'
      path: '/subscribers'
      fullPath: '/channel/subscribers'
      preLoaderRoute: typeof ChannelSubscribersRouteImport
      parentRoute: typeof ChannelRoute
    }
    '/channel/videos': {
      id: '/channel/videos'
      path: '/videos'
      fullPath: '/channel/videos'
      preLoaderRoute: typeof ChannelVideosRouteImport
      parentRoute: typeof ChannelRoute
    }
    '/downloads/$downloadId': {
      id: '/downloads/$downloadId'
      path: '/downloads/$downloadId'
      fullPath: '/downloads/$downloadId'
      preLoaderRoute: typeof DownloadsDownloadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moment/': {
      id: '/moment/'
      path: '/moment'
      fullPath: '/moment/'
      preLoaderRoute: typeof MomentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moment/$momentId': {
      id: '/moment/$momentId'
      path: '/moment/$momentId'
      fullPath: '/moment/$momentId'
      preLoaderRoute: typeof MomentMomentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moment/create': {
      id: '/moment/create'
      path: '/moment/create'
      fullPath: '/moment/create'
      preLoaderRoute: typeof MomentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orbit/': {
      id: '/orbit/'
      path: '/'
      fullPath: '/orbit/'
      preLoaderRoute: typeof OrbitIndexRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/$profileId': {
      id: '/orbit/$profileId'
      path: '/$profileId'
      fullPath: '/orbit/$profileId'
      preLoaderRoute: typeof OrbitProfileIdRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/create': {
      id: '/orbit/create'
      path: '/create'
      fullPath: '/orbit/create'
      preLoaderRoute: typeof OrbitCreateRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/me': {
      id: '/orbit/me'
      path: '/me'
      fullPath: '/orbit/me'
      preLoaderRoute: typeof OrbitMeRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/messages': {
      id: '/orbit/messages'
      path: '/messages'
      fullPath: '/orbit/messages'
      preLoaderRoute: typeof OrbitMessagesRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/notifications': {
      id: '/orbit/notifications'
      path: '/notifications'
      fullPath: '/orbit/notifications'
      preLoaderRoute: typeof OrbitNotificationsRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/privacy': {
      id: '/orbit/privacy'
      path: '/privacy'
      fullPath: '/orbit/privacy'
      preLoaderRoute: typeof OrbitPrivacyRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/post/create': {
      id: '/post/create'
      path: '/post/create'
      fullPath: '/post/create'
      preLoaderRoute: typeof PostCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reel/$reelId': {
      id: '/reel/$reelId'
      path: '/reel/$reelId'
      fullPath: '/reel/$reelId'
      preLoaderRoute: typeof ReelReelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/monetization': {
      id: '/terms/monetization'
      path: '/monetization'
      fullPath: '/terms/monetization'
      preLoaderRoute: typeof TermsMonetizationRouteImport
      parentRoute: typeof TermsRoute
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$videoId': {
      id: '/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof VideoVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/upload': {
      id: '/video/upload'
      path: '/video/upload'
      fullPath: '/video/upload'
      preLoaderRoute: typeof VideoUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/orbit/chat/$userId': {
      id: '/orbit/chat/$userId'
      path: '/chat/$userId'
      fullPath: '/orbit/chat/$userId'
      preLoaderRoute: typeof OrbitChatUserIdRouteImport
      parentRoute: typeof OrbitRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminCopyrightReportsRoute: typeof AdminCopyrightReportsRoute
  AdminSportsVerificationRoute: typeof AdminSportsVerificationRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCopyrightReportsRoute: AdminCopyrightReportsRoute,
  AdminSportsVerificationRoute: AdminSportsVerificationRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ChannelRouteChildren {
  ChannelAnalyticsRoute: typeof ChannelAnalyticsRoute
  ChannelCreateRoute: typeof ChannelCreateRoute
  ChannelMonetizationRoute: typeof ChannelMonetizationRoute
  ChannelPostsRoute: typeof ChannelPostsRoute
  ChannelReelsRoute: typeof ChannelReelsRoute
  ChannelSubscribersRoute: typeof ChannelSubscribersRoute
  ChannelVideosRoute: typeof ChannelVideosRoute
  ChannelIndexRoute: typeof ChannelIndexRoute
}

const ChannelRouteChildren: ChannelRouteChildren = {
  ChannelAnalyticsRoute: ChannelAnalyticsRoute,
  ChannelCreateRoute: ChannelCreateRoute,
  ChannelMonetizationRoute: ChannelMonetizationRoute,
  ChannelPostsRoute: ChannelPostsRoute,
  ChannelReelsRoute: ChannelReelsRoute,
  ChannelSubscribersRoute: ChannelSubscribersRoute,
  ChannelVideosRoute: ChannelVideosRoute,
  ChannelIndexRoute: ChannelIndexRoute,
}

const ChannelRouteWithChildren =
  ChannelRoute._addFileChildren(ChannelRouteChildren)

interface OrbitRouteChildren {
  OrbitProfileIdRoute: typeof OrbitProfileIdRoute
  OrbitCreateRoute: typeof OrbitCreateRoute
  OrbitMeRoute: typeof OrbitMeRoute
  OrbitMessagesRoute: typeof OrbitMessagesRoute
  OrbitNotificationsRoute: typeof OrbitNotificationsRoute
  OrbitPrivacyRoute: typeof OrbitPrivacyRoute
  OrbitIndexRoute: typeof OrbitIndexRoute
  OrbitChatUserIdRoute: typeof OrbitChatUserIdRoute
}

const OrbitRouteChildren: OrbitRouteChildren = {
  OrbitProfileIdRoute: OrbitProfileIdRoute,
  OrbitCreateRoute: OrbitCreateRoute,
  OrbitMeRoute: OrbitMeRoute,
  OrbitMessagesRoute: OrbitMessagesRoute,
  OrbitNotificationsRoute: OrbitNotificationsRoute,
  OrbitPrivacyRoute: OrbitPrivacyRoute,
  OrbitIndexRoute: OrbitIndexRoute,
  OrbitChatUserIdRoute: OrbitChatUserIdRoute,
}

const OrbitRouteWithChildren = OrbitRoute._addFileChildren(OrbitRouteChildren)

interface TermsRouteChildren {
  TermsMonetizationRoute: typeof TermsMonetizationRoute
}

const TermsRouteChildren: TermsRouteChildren = {
  TermsMonetizationRoute: TermsMonetizationRoute,
}

const TermsRouteWithChildren = TermsRoute._addFileChildren(TermsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ChannelRoute: ChannelRouteWithChildren,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  CopyrightPolicyRoute: CopyrightPolicyRoute,
  CreateRoute: CreateRoute,
  HelpCenterRoute: HelpCenterRoute,
  LicensesRoute: LicensesRoute,
  NotificationsRoute: NotificationsRoute,
  OrbitRoute: OrbitRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReelsRoute: ReelsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRouteWithChildren,
  Verify2faRoute: Verify2faRoute,
  WalletRoute: WalletRoute,
  DownloadsDownloadIdRoute: DownloadsDownloadIdRoute,
  MomentMomentIdRoute: MomentMomentIdRoute,
  MomentCreateRoute: MomentCreateRoute,
  PostCreateRoute: PostCreateRoute,
  ReelReelIdRoute: ReelReelIdRoute,
  UUserIdRoute: UUserIdRoute,
  VideoVideoIdRoute: VideoVideoIdRoute,
  VideoUploadRoute: VideoUploadRoute,
  MomentIndexRoute: MomentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
